---
title: "Coursera Project Codebook"
author: "David Parker"
date: "Sunday, July 27, 2014"
---
```        
codebook geerated for data imported "Data Science, Wearable Computing" experiment. The data from this experimenttitled "Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine"

Merged data from raw data files features.txt, activity_labels.txt, features_info.txt
Description from features_info.txt:
```         
Feature Selection 
=================

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. 
These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. 
Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. 
Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). 
Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.  

==============================================================================================    
Fields from raw data import, activity_labels.txt:                                                       
==============================================================================================    

```         
-----------------------      
N|Activity            |      
-----------------------      
1 WALKING
2 WALKING_UPSTAIRS
3 WALKING_DOWNSTAIRS
4 SITTING
5 STANDING
6 LAYING
```      
==============================================================================================    
Fields from raw data import, features.txt:                                                       
==============================================================================================    
```         
-------------------------------------------|-------------------------------------------
N| field.name                              | field.description                        |
-|-----------------------------------------|-------------------------------------------
1 tBodyAcc-mean()-X
2 tBodyAcc-mean()-Y
3 tBodyAcc-mean()-Z
4 tBodyAcc-std()-X
5 tBodyAcc-std()-Y
6 tBodyAcc-std()-Z
7 tBodyAcc-mad()-X
8 tBodyAcc-mad()-Y
9 tBodyAcc-mad()-Z
10 tBodyAcc-max()-X
11 tBodyAcc-max()-Y
12 tBodyAcc-max()-Z
13 tBodyAcc-min()-X
14 tBodyAcc-min()-Y
15 tBodyAcc-min()-Z
16 tBodyAcc-sma()
17 tBodyAcc-energy()-X
18 tBodyAcc-energy()-Y
19 tBodyAcc-energy()-Z
20 tBodyAcc-iqr()-X
21 tBodyAcc-iqr()-Y
22 tBodyAcc-iqr()-Z
23 tBodyAcc-entropy()-X
24 tBodyAcc-entropy()-Y
25 tBodyAcc-entropy()-Z
26 tBodyAcc-arCoeff()-X,1
27 tBodyAcc-arCoeff()-X,2
28 tBodyAcc-arCoeff()-X,3
29 tBodyAcc-arCoeff()-X,4
30 tBodyAcc-arCoeff()-Y,1
31 tBodyAcc-arCoeff()-Y,2
32 tBodyAcc-arCoeff()-Y,3
33 tBodyAcc-arCoeff()-Y,4
34 tBodyAcc-arCoeff()-Z,1
35 tBodyAcc-arCoeff()-Z,2
36 tBodyAcc-arCoeff()-Z,3
37 tBodyAcc-arCoeff()-Z,4
38 tBodyAcc-correlation()-X,Y
39 tBodyAcc-correlation()-X,Z
40 tBodyAcc-correlation()-Y,Z
41 tGravityAcc-mean()-X
42 tGravityAcc-mean()-Y
43 tGravityAcc-mean()-Z
44 tGravityAcc-std()-X
45 tGravityAcc-std()-Y
46 tGravityAcc-std()-Z
47 tGravityAcc-mad()-X
48 tGravityAcc-mad()-Y
49 tGravityAcc-mad()-Z
50 tGravityAcc-max()-X
51 tGravityAcc-max()-Y
52 tGravityAcc-max()-Z
53 tGravityAcc-min()-X
54 tGravityAcc-min()-Y
55 tGravityAcc-min()-Z
56 tGravityAcc-sma()
57 tGravityAcc-energy()-X
58 tGravityAcc-energy()-Y
59 tGravityAcc-energy()-Z
60 tGravityAcc-iqr()-X
61 tGravityAcc-iqr()-Y
62 tGravityAcc-iqr()-Z
63 tGravityAcc-entropy()-X
64 tGravityAcc-entropy()-Y
65 tGravityAcc-entropy()-Z
66 tGravityAcc-arCoeff()-X,1
67 tGravityAcc-arCoeff()-X,2
68 tGravityAcc-arCoeff()-X,3
69 tGravityAcc-arCoeff()-X,4
70 tGravityAcc-arCoeff()-Y,1
71 tGravityAcc-arCoeff()-Y,2
72 tGravityAcc-arCoeff()-Y,3
73 tGravityAcc-arCoeff()-Y,4
74 tGravityAcc-arCoeff()-Z,1
75 tGravityAcc-arCoeff()-Z,2
76 tGravityAcc-arCoeff()-Z,3
77 tGravityAcc-arCoeff()-Z,4
78 tGravityAcc-correlation()-X,Y
79 tGravityAcc-correlation()-X,Z
80 tGravityAcc-correlation()-Y,Z
81 tBodyAccJerk-mean()-X
82 tBodyAccJerk-mean()-Y
83 tBodyAccJerk-mean()-Z
84 tBodyAccJerk-std()-X
85 tBodyAccJerk-std()-Y
86 tBodyAccJerk-std()-Z
87 tBodyAccJerk-mad()-X
88 tBodyAccJerk-mad()-Y
89 tBodyAccJerk-mad()-Z
90 tBodyAccJerk-max()-X
91 tBodyAccJerk-max()-Y
92 tBodyAccJerk-max()-Z
93 tBodyAccJerk-min()-X
94 tBodyAccJerk-min()-Y
95 tBodyAccJerk-min()-Z
96 tBodyAccJerk-sma()
97 tBodyAccJerk-energy()-X
98 tBodyAccJerk-energy()-Y
99 tBodyAccJerk-energy()-Z
100 tBodyAccJerk-iqr()-X
101 tBodyAccJerk-iqr()-Y
102 tBodyAccJerk-iqr()-Z
103 tBodyAccJerk-entropy()-X
104 tBodyAccJerk-entropy()-Y
105 tBodyAccJerk-entropy()-Z
106 tBodyAccJerk-arCoeff()-X,1
107 tBodyAccJerk-arCoeff()-X,2
108 tBodyAccJerk-arCoeff()-X,3
109 tBodyAccJerk-arCoeff()-X,4
110 tBodyAccJerk-arCoeff()-Y,1
111 tBodyAccJerk-arCoeff()-Y,2
112 tBodyAccJerk-arCoeff()-Y,3
113 tBodyAccJerk-arCoeff()-Y,4
114 tBodyAccJerk-arCoeff()-Z,1
115 tBodyAccJerk-arCoeff()-Z,2
116 tBodyAccJerk-arCoeff()-Z,3
117 tBodyAccJerk-arCoeff()-Z,4
118 tBodyAccJerk-correlation()-X,Y
119 tBodyAccJerk-correlation()-X,Z
120 tBodyAccJerk-correlation()-Y,Z
121 tBodyGyro-mean()-X
122 tBodyGyro-mean()-Y
123 tBodyGyro-mean()-Z
124 tBodyGyro-std()-X
125 tBodyGyro-std()-Y
126 tBodyGyro-std()-Z
127 tBodyGyro-mad()-X
128 tBodyGyro-mad()-Y
129 tBodyGyro-mad()-Z
130 tBodyGyro-max()-X
131 tBodyGyro-max()-Y
132 tBodyGyro-max()-Z
133 tBodyGyro-min()-X
134 tBodyGyro-min()-Y
135 tBodyGyro-min()-Z
136 tBodyGyro-sma()
137 tBodyGyro-energy()-X
138 tBodyGyro-energy()-Y
139 tBodyGyro-energy()-Z
140 tBodyGyro-iqr()-X
141 tBodyGyro-iqr()-Y
142 tBodyGyro-iqr()-Z
143 tBodyGyro-entropy()-X
144 tBodyGyro-entropy()-Y
145 tBodyGyro-entropy()-Z
146 tBodyGyro-arCoeff()-X,1
147 tBodyGyro-arCoeff()-X,2
148 tBodyGyro-arCoeff()-X,3
149 tBodyGyro-arCoeff()-X,4
150 tBodyGyro-arCoeff()-Y,1
151 tBodyGyro-arCoeff()-Y,2
152 tBodyGyro-arCoeff()-Y,3
153 tBodyGyro-arCoeff()-Y,4
154 tBodyGyro-arCoeff()-Z,1
155 tBodyGyro-arCoeff()-Z,2
156 tBodyGyro-arCoeff()-Z,3
157 tBodyGyro-arCoeff()-Z,4
158 tBodyGyro-correlation()-X,Y
159 tBodyGyro-correlation()-X,Z
160 tBodyGyro-correlation()-Y,Z
161 tBodyGyroJerk-mean()-X
162 tBodyGyroJerk-mean()-Y
163 tBodyGyroJerk-mean()-Z
164 tBodyGyroJerk-std()-X
165 tBodyGyroJerk-std()-Y
166 tBodyGyroJerk-std()-Z
167 tBodyGyroJerk-mad()-X
168 tBodyGyroJerk-mad()-Y
169 tBodyGyroJerk-mad()-Z
170 tBodyGyroJerk-max()-X
171 tBodyGyroJerk-max()-Y
172 tBodyGyroJerk-max()-Z
173 tBodyGyroJerk-min()-X
174 tBodyGyroJerk-min()-Y
175 tBodyGyroJerk-min()-Z
176 tBodyGyroJerk-sma()
177 tBodyGyroJerk-energy()-X
178 tBodyGyroJerk-energy()-Y
179 tBodyGyroJerk-energy()-Z
180 tBodyGyroJerk-iqr()-X
181 tBodyGyroJerk-iqr()-Y
182 tBodyGyroJerk-iqr()-Z
183 tBodyGyroJerk-entropy()-X
184 tBodyGyroJerk-entropy()-Y
185 tBodyGyroJerk-entropy()-Z
186 tBodyGyroJerk-arCoeff()-X,1
187 tBodyGyroJerk-arCoeff()-X,2
188 tBodyGyroJerk-arCoeff()-X,3
189 tBodyGyroJerk-arCoeff()-X,4
190 tBodyGyroJerk-arCoeff()-Y,1
191 tBodyGyroJerk-arCoeff()-Y,2
192 tBodyGyroJerk-arCoeff()-Y,3
193 tBodyGyroJerk-arCoeff()-Y,4
194 tBodyGyroJerk-arCoeff()-Z,1
195 tBodyGyroJerk-arCoeff()-Z,2
196 tBodyGyroJerk-arCoeff()-Z,3
197 tBodyGyroJerk-arCoeff()-Z,4
198 tBodyGyroJerk-correlation()-X,Y
199 tBodyGyroJerk-correlation()-X,Z
200 tBodyGyroJerk-correlation()-Y,Z
201 tBodyAccMag-mean()
202 tBodyAccMag-std()
203 tBodyAccMag-mad()
204 tBodyAccMag-max()
205 tBodyAccMag-min()
206 tBodyAccMag-sma()
207 tBodyAccMag-energy()
208 tBodyAccMag-iqr()
209 tBodyAccMag-entropy()
210 tBodyAccMag-arCoeff()1
211 tBodyAccMag-arCoeff()2
212 tBodyAccMag-arCoeff()3
213 tBodyAccMag-arCoeff()4
214 tGravityAccMag-mean()
215 tGravityAccMag-std()
216 tGravityAccMag-mad()
217 tGravityAccMag-max()
218 tGravityAccMag-min()
219 tGravityAccMag-sma()
220 tGravityAccMag-energy()
221 tGravityAccMag-iqr()
222 tGravityAccMag-entropy()
223 tGravityAccMag-arCoeff()1
224 tGravityAccMag-arCoeff()2
225 tGravityAccMag-arCoeff()3
226 tGravityAccMag-arCoeff()4
227 tBodyAccJerkMag-mean()
228 tBodyAccJerkMag-std()
229 tBodyAccJerkMag-mad()
230 tBodyAccJerkMag-max()
231 tBodyAccJerkMag-min()
232 tBodyAccJerkMag-sma()
233 tBodyAccJerkMag-energy()
234 tBodyAccJerkMag-iqr()
235 tBodyAccJerkMag-entropy()
236 tBodyAccJerkMag-arCoeff()1
237 tBodyAccJerkMag-arCoeff()2
238 tBodyAccJerkMag-arCoeff()3
239 tBodyAccJerkMag-arCoeff()4
240 tBodyGyroMag-mean()
241 tBodyGyroMag-std()
242 tBodyGyroMag-mad()
243 tBodyGyroMag-max()
244 tBodyGyroMag-min()
245 tBodyGyroMag-sma()
246 tBodyGyroMag-energy()
247 tBodyGyroMag-iqr()
248 tBodyGyroMag-entropy()
249 tBodyGyroMag-arCoeff()1
250 tBodyGyroMag-arCoeff()2
251 tBodyGyroMag-arCoeff()3
252 tBodyGyroMag-arCoeff()4
253 tBodyGyroJerkMag-mean()
254 tBodyGyroJerkMag-std()
255 tBodyGyroJerkMag-mad()
256 tBodyGyroJerkMag-max()
257 tBodyGyroJerkMag-min()
258 tBodyGyroJerkMag-sma()
259 tBodyGyroJerkMag-energy()
260 tBodyGyroJerkMag-iqr()
261 tBodyGyroJerkMag-entropy()
262 tBodyGyroJerkMag-arCoeff()1
263 tBodyGyroJerkMag-arCoeff()2
264 tBodyGyroJerkMag-arCoeff()3
265 tBodyGyroJerkMag-arCoeff()4
266 fBodyAcc-mean()-X
267 fBodyAcc-mean()-Y
268 fBodyAcc-mean()-Z
269 fBodyAcc-std()-X
270 fBodyAcc-std()-Y
271 fBodyAcc-std()-Z
272 fBodyAcc-mad()-X
273 fBodyAcc-mad()-Y
274 fBodyAcc-mad()-Z
275 fBodyAcc-max()-X
276 fBodyAcc-max()-Y
277 fBodyAcc-max()-Z
278 fBodyAcc-min()-X
279 fBodyAcc-min()-Y
280 fBodyAcc-min()-Z
281 fBodyAcc-sma()
282 fBodyAcc-energy()-X
283 fBodyAcc-energy()-Y
284 fBodyAcc-energy()-Z
285 fBodyAcc-iqr()-X
286 fBodyAcc-iqr()-Y
287 fBodyAcc-iqr()-Z
288 fBodyAcc-entropy()-X
289 fBodyAcc-entropy()-Y
290 fBodyAcc-entropy()-Z
291 fBodyAcc-maxInds-X
292 fBodyAcc-maxInds-Y
293 fBodyAcc-maxInds-Z
294 fBodyAcc-meanFreq()-X
295 fBodyAcc-meanFreq()-Y
296 fBodyAcc-meanFreq()-Z
297 fBodyAcc-skewness()-X
298 fBodyAcc-kurtosis()-X
299 fBodyAcc-skewness()-Y
300 fBodyAcc-kurtosis()-Y
301 fBodyAcc-skewness()-Z
302 fBodyAcc-kurtosis()-Z
303 fBodyAcc-bandsEnergy()-1,8
304 fBodyAcc-bandsEnergy()-9,16
305 fBodyAcc-bandsEnergy()-17,24
306 fBodyAcc-bandsEnergy()-25,32
307 fBodyAcc-bandsEnergy()-33,40
308 fBodyAcc-bandsEnergy()-41,48
309 fBodyAcc-bandsEnergy()-49,56
310 fBodyAcc-bandsEnergy()-57,64
311 fBodyAcc-bandsEnergy()-1,16
312 fBodyAcc-bandsEnergy()-17,32
313 fBodyAcc-bandsEnergy()-33,48
314 fBodyAcc-bandsEnergy()-49,64
315 fBodyAcc-bandsEnergy()-1,24
316 fBodyAcc-bandsEnergy()-25,48
317 fBodyAcc-bandsEnergy()-1,8
318 fBodyAcc-bandsEnergy()-9,16
319 fBodyAcc-bandsEnergy()-17,24
320 fBodyAcc-bandsEnergy()-25,32
321 fBodyAcc-bandsEnergy()-33,40
322 fBodyAcc-bandsEnergy()-41,48
323 fBodyAcc-bandsEnergy()-49,56
324 fBodyAcc-bandsEnergy()-57,64
325 fBodyAcc-bandsEnergy()-1,16
326 fBodyAcc-bandsEnergy()-17,32
327 fBodyAcc-bandsEnergy()-33,48
328 fBodyAcc-bandsEnergy()-49,64
329 fBodyAcc-bandsEnergy()-1,24
330 fBodyAcc-bandsEnergy()-25,48
331 fBodyAcc-bandsEnergy()-1,8
332 fBodyAcc-bandsEnergy()-9,16
333 fBodyAcc-bandsEnergy()-17,24
334 fBodyAcc-bandsEnergy()-25,32
335 fBodyAcc-bandsEnergy()-33,40
336 fBodyAcc-bandsEnergy()-41,48
337 fBodyAcc-bandsEnergy()-49,56
338 fBodyAcc-bandsEnergy()-57,64
339 fBodyAcc-bandsEnergy()-1,16
340 fBodyAcc-bandsEnergy()-17,32
341 fBodyAcc-bandsEnergy()-33,48
342 fBodyAcc-bandsEnergy()-49,64
343 fBodyAcc-bandsEnergy()-1,24
344 fBodyAcc-bandsEnergy()-25,48
345 fBodyAccJerk-mean()-X
346 fBodyAccJerk-mean()-Y
347 fBodyAccJerk-mean()-Z
348 fBodyAccJerk-std()-X
349 fBodyAccJerk-std()-Y
350 fBodyAccJerk-std()-Z
351 fBodyAccJerk-mad()-X
352 fBodyAccJerk-mad()-Y
353 fBodyAccJerk-mad()-Z
354 fBodyAccJerk-max()-X
355 fBodyAccJerk-max()-Y
356 fBodyAccJerk-max()-Z
357 fBodyAccJerk-min()-X
358 fBodyAccJerk-min()-Y
359 fBodyAccJerk-min()-Z
360 fBodyAccJerk-sma()
361 fBodyAccJerk-energy()-X
362 fBodyAccJerk-energy()-Y
363 fBodyAccJerk-energy()-Z
364 fBodyAccJerk-iqr()-X
365 fBodyAccJerk-iqr()-Y
366 fBodyAccJerk-iqr()-Z
367 fBodyAccJerk-entropy()-X
368 fBodyAccJerk-entropy()-Y
369 fBodyAccJerk-entropy()-Z
370 fBodyAccJerk-maxInds-X
371 fBodyAccJerk-maxInds-Y
372 fBodyAccJerk-maxInds-Z
373 fBodyAccJerk-meanFreq()-X
374 fBodyAccJerk-meanFreq()-Y
375 fBodyAccJerk-meanFreq()-Z
376 fBodyAccJerk-skewness()-X
377 fBodyAccJerk-kurtosis()-X
378 fBodyAccJerk-skewness()-Y
379 fBodyAccJerk-kurtosis()-Y
380 fBodyAccJerk-skewness()-Z
381 fBodyAccJerk-kurtosis()-Z
382 fBodyAccJerk-bandsEnergy()-1,8
383 fBodyAccJerk-bandsEnergy()-9,16
384 fBodyAccJerk-bandsEnergy()-17,24
385 fBodyAccJerk-bandsEnergy()-25,32
386 fBodyAccJerk-bandsEnergy()-33,40
387 fBodyAccJerk-bandsEnergy()-41,48
388 fBodyAccJerk-bandsEnergy()-49,56
389 fBodyAccJerk-bandsEnergy()-57,64
390 fBodyAccJerk-bandsEnergy()-1,16
391 fBodyAccJerk-bandsEnergy()-17,32
392 fBodyAccJerk-bandsEnergy()-33,48
393 fBodyAccJerk-bandsEnergy()-49,64
394 fBodyAccJerk-bandsEnergy()-1,24
395 fBodyAccJerk-bandsEnergy()-25,48
396 fBodyAccJerk-bandsEnergy()-1,8
397 fBodyAccJerk-bandsEnergy()-9,16
398 fBodyAccJerk-bandsEnergy()-17,24
399 fBodyAccJerk-bandsEnergy()-25,32
400 fBodyAccJerk-bandsEnergy()-33,40
401 fBodyAccJerk-bandsEnergy()-41,48
402 fBodyAccJerk-bandsEnergy()-49,56
403 fBodyAccJerk-bandsEnergy()-57,64
404 fBodyAccJerk-bandsEnergy()-1,16
405 fBodyAccJerk-bandsEnergy()-17,32
406 fBodyAccJerk-bandsEnergy()-33,48
407 fBodyAccJerk-bandsEnergy()-49,64
408 fBodyAccJerk-bandsEnergy()-1,24
409 fBodyAccJerk-bandsEnergy()-25,48
410 fBodyAccJerk-bandsEnergy()-1,8
411 fBodyAccJerk-bandsEnergy()-9,16
412 fBodyAccJerk-bandsEnergy()-17,24
413 fBodyAccJerk-bandsEnergy()-25,32
414 fBodyAccJerk-bandsEnergy()-33,40
415 fBodyAccJerk-bandsEnergy()-41,48
416 fBodyAccJerk-bandsEnergy()-49,56
417 fBodyAccJerk-bandsEnergy()-57,64
418 fBodyAccJerk-bandsEnergy()-1,16
419 fBodyAccJerk-bandsEnergy()-17,32
420 fBodyAccJerk-bandsEnergy()-33,48
421 fBodyAccJerk-bandsEnergy()-49,64
422 fBodyAccJerk-bandsEnergy()-1,24
423 fBodyAccJerk-bandsEnergy()-25,48
424 fBodyGyro-mean()-X
425 fBodyGyro-mean()-Y
426 fBodyGyro-mean()-Z
427 fBodyGyro-std()-X
428 fBodyGyro-std()-Y
429 fBodyGyro-std()-Z
430 fBodyGyro-mad()-X
431 fBodyGyro-mad()-Y
432 fBodyGyro-mad()-Z
433 fBodyGyro-max()-X
434 fBodyGyro-max()-Y
435 fBodyGyro-max()-Z
436 fBodyGyro-min()-X
437 fBodyGyro-min()-Y
438 fBodyGyro-min()-Z
439 fBodyGyro-sma()
440 fBodyGyro-energy()-X
441 fBodyGyro-energy()-Y
442 fBodyGyro-energy()-Z
443 fBodyGyro-iqr()-X
444 fBodyGyro-iqr()-Y
445 fBodyGyro-iqr()-Z
446 fBodyGyro-entropy()-X
447 fBodyGyro-entropy()-Y
448 fBodyGyro-entropy()-Z
449 fBodyGyro-maxInds-X
450 fBodyGyro-maxInds-Y
451 fBodyGyro-maxInds-Z
452 fBodyGyro-meanFreq()-X
453 fBodyGyro-meanFreq()-Y
454 fBodyGyro-meanFreq()-Z
455 fBodyGyro-skewness()-X
456 fBodyGyro-kurtosis()-X
457 fBodyGyro-skewness()-Y
458 fBodyGyro-kurtosis()-Y
459 fBodyGyro-skewness()-Z
460 fBodyGyro-kurtosis()-Z
461 fBodyGyro-bandsEnergy()-1,8
462 fBodyGyro-bandsEnergy()-9,16
463 fBodyGyro-bandsEnergy()-17,24
464 fBodyGyro-bandsEnergy()-25,32
465 fBodyGyro-bandsEnergy()-33,40
466 fBodyGyro-bandsEnergy()-41,48
467 fBodyGyro-bandsEnergy()-49,56
468 fBodyGyro-bandsEnergy()-57,64
469 fBodyGyro-bandsEnergy()-1,16
470 fBodyGyro-bandsEnergy()-17,32
471 fBodyGyro-bandsEnergy()-33,48
472 fBodyGyro-bandsEnergy()-49,64
473 fBodyGyro-bandsEnergy()-1,24
474 fBodyGyro-bandsEnergy()-25,48
475 fBodyGyro-bandsEnergy()-1,8
476 fBodyGyro-bandsEnergy()-9,16
477 fBodyGyro-bandsEnergy()-17,24
478 fBodyGyro-bandsEnergy()-25,32
479 fBodyGyro-bandsEnergy()-33,40
480 fBodyGyro-bandsEnergy()-41,48
481 fBodyGyro-bandsEnergy()-49,56
482 fBodyGyro-bandsEnergy()-57,64
483 fBodyGyro-bandsEnergy()-1,16
484 fBodyGyro-bandsEnergy()-17,32
485 fBodyGyro-bandsEnergy()-33,48
486 fBodyGyro-bandsEnergy()-49,64
487 fBodyGyro-bandsEnergy()-1,24
488 fBodyGyro-bandsEnergy()-25,48
489 fBodyGyro-bandsEnergy()-1,8
490 fBodyGyro-bandsEnergy()-9,16
491 fBodyGyro-bandsEnergy()-17,24
492 fBodyGyro-bandsEnergy()-25,32
493 fBodyGyro-bandsEnergy()-33,40
494 fBodyGyro-bandsEnergy()-41,48
495 fBodyGyro-bandsEnergy()-49,56
496 fBodyGyro-bandsEnergy()-57,64
497 fBodyGyro-bandsEnergy()-1,16
498 fBodyGyro-bandsEnergy()-17,32
499 fBodyGyro-bandsEnergy()-33,48
500 fBodyGyro-bandsEnergy()-49,64
501 fBodyGyro-bandsEnergy()-1,24
502 fBodyGyro-bandsEnergy()-25,48
503 fBodyAccMag-mean()
504 fBodyAccMag-std()
505 fBodyAccMag-mad()
506 fBodyAccMag-max()
507 fBodyAccMag-min()
508 fBodyAccMag-sma()
509 fBodyAccMag-energy()
510 fBodyAccMag-iqr()
511 fBodyAccMag-entropy()
512 fBodyAccMag-maxInds
513 fBodyAccMag-meanFreq()
514 fBodyAccMag-skewness()
515 fBodyAccMag-kurtosis()
516 fBodyBodyAccJerkMag-mean()
517 fBodyBodyAccJerkMag-std()
518 fBodyBodyAccJerkMag-mad()
519 fBodyBodyAccJerkMag-max()
520 fBodyBodyAccJerkMag-min()
521 fBodyBodyAccJerkMag-sma()
522 fBodyBodyAccJerkMag-energy()
523 fBodyBodyAccJerkMag-iqr()
524 fBodyBodyAccJerkMag-entropy()
525 fBodyBodyAccJerkMag-maxInds
526 fBodyBodyAccJerkMag-meanFreq()
527 fBodyBodyAccJerkMag-skewness()
528 fBodyBodyAccJerkMag-kurtosis()
529 fBodyBodyGyroMag-mean()
530 fBodyBodyGyroMag-std()
531 fBodyBodyGyroMag-mad()
532 fBodyBodyGyroMag-max()
533 fBodyBodyGyroMag-min()
534 fBodyBodyGyroMag-sma()
535 fBodyBodyGyroMag-energy()
536 fBodyBodyGyroMag-iqr()
537 fBodyBodyGyroMag-entropy()
538 fBodyBodyGyroMag-maxInds
539 fBodyBodyGyroMag-meanFreq()
540 fBodyBodyGyroMag-skewness()
541 fBodyBodyGyroMag-kurtosis()
542 fBodyBodyGyroJerkMag-mean()
543 fBodyBodyGyroJerkMag-std()
544 fBodyBodyGyroJerkMag-mad()
545 fBodyBodyGyroJerkMag-max()
546 fBodyBodyGyroJerkMag-min()
547 fBodyBodyGyroJerkMag-sma()
548 fBodyBodyGyroJerkMag-energy()
549 fBodyBodyGyroJerkMag-iqr()
550 fBodyBodyGyroJerkMag-entropy()
551 fBodyBodyGyroJerkMag-maxInds
552 fBodyBodyGyroJerkMag-meanFreq()
553 fBodyBodyGyroJerkMag-skewness()
554 fBodyBodyGyroJerkMag-kurtosis()
555 angle(tBodyAccMean,gravity)
556 angle(tBodyAccJerkMean),gravityMean)
557 angle(tBodyGyroMean,gravityMean)
558 angle(tBodyGyroJerkMean,gravityMean)
559 angle(X,gravityMean)
560 angle(Y,gravityMean)
561 angle(Z,gravityMean)
```                     
==============================================================================================         
| Results of all raw data merged into 1 data.frame.                                  
| Data prior to any Tidy Data processing                                               
==============================================================================================         
| data.frame: xMergData                                                           
==============================================================================================         
```                                                
str(xMergeData, list.len = 9999)                         
'data.frame':    10299 obs. of  563 variables:           
----------------------------------------------------------------------------------------------   
 $ tBodyAcc.mean...X                   : num  0.289 0.278 0.28 0.279 0.277 ...
 $ tBodyAcc.mean...Y                   : num  -0.0203 -0.0164 -0.0195 -0.0262 -0.0166 ...
 $ tBodyAcc.mean...Z                   : num  -0.133 -0.124 -0.113 -0.123 -0.115 ...
 $ tBodyAcc.std...X                    : num  -0.995 -0.998 -0.995 -0.996 -0.998 ...
 $ tBodyAcc.std...Y                    : num  -0.983 -0.975 -0.967 -0.983 -0.981 ...
 $ tBodyAcc.std...Z                    : num  -0.914 -0.96 -0.979 -0.991 -0.99 ...
 $ tBodyAcc.mad...X                    : num  -0.995 -0.999 -0.997 -0.997 -0.998 ...
 $ tBodyAcc.mad...Y                    : num  -0.983 -0.975 -0.964 -0.983 -0.98 ...
 $ tBodyAcc.mad...Z                    : num  -0.924 -0.958 -0.977 -0.989 -0.99 ...
 $ tBodyAcc.max...X                    : num  -0.935 -0.943 -0.939 -0.939 -0.942 ...
 $ tBodyAcc.max...Y                    : num  -0.567 -0.558 -0.558 -0.576 -0.569 ...
 $ tBodyAcc.max...Z                    : num  -0.744 -0.818 -0.818 -0.83 -0.825 ...
 $ tBodyAcc.min...X                    : num  0.853 0.849 0.844 0.844 0.849 ...
 $ tBodyAcc.min...Y                    : num  0.686 0.686 0.682 0.682 0.683 ...
 $ tBodyAcc.min...Z                    : num  0.814 0.823 0.839 0.838 0.838 ...
 $ tBodyAcc.sma..                      : num  -0.966 -0.982 -0.983 -0.986 -0.993 ...
 $ tBodyAcc.energy...X                 : num  -1 -1 -1 -1 -1 ...
 $ tBodyAcc.energy...Y                 : num  -1 -1 -1 -1 -1 ...
 $ tBodyAcc.energy...Z                 : num  -0.995 -0.998 -0.999 -1 -1 ...
 $ tBodyAcc.iqr...X                    : num  -0.994 -0.999 -0.997 -0.997 -0.998 ...
 $ tBodyAcc.iqr...Y                    : num  -0.988 -0.978 -0.965 -0.984 -0.981 ...
 $ tBodyAcc.iqr...Z                    : num  -0.943 -0.948 -0.975 -0.986 -0.991 ...
 $ tBodyAcc.entropy...X                : num  -0.408 -0.715 -0.592 -0.627 -0.787 ...
 $ tBodyAcc.entropy...Y                : num  -0.679 -0.501 -0.486 -0.851 -0.559 ...
 $ tBodyAcc.entropy...Z                : num  -0.602 -0.571 -0.571 -0.912 -0.761 ...
 $ tBodyAcc.arCoeff...X.1              : num  0.9293 0.6116 0.273 0.0614 0.3133 ...
 $ tBodyAcc.arCoeff...X.2              : num  -0.853 -0.3295 -0.0863 0.0748 -0.1312 ...
 $ tBodyAcc.arCoeff...X.3              : num  0.36 0.284 0.337 0.198 0.191 ...
 $ tBodyAcc.arCoeff...X.4              : num  -0.0585 0.2846 -0.1647 -0.2643 0.0869 ...
 $ tBodyAcc.arCoeff...Y.1              : num  0.2569 0.1157 0.0172 0.0725 0.2576 ...
 $ tBodyAcc.arCoeff...Y.2              : num  -0.2248 -0.091 -0.0745 -0.1553 -0.2725 ...
 $ tBodyAcc.arCoeff...Y.3              : num  0.264 0.294 0.342 0.323 0.435 ...
 $ tBodyAcc.arCoeff...Y.4              : num  -0.0952 -0.2812 -0.3326 -0.1708 -0.3154 ...
 $ tBodyAcc.arCoeff...Z.1              : num  0.279 0.086 0.239 0.295 0.44 ...
 $ tBodyAcc.arCoeff...Z.2              : num  -0.4651 -0.0222 -0.1362 -0.3061 -0.2691 ...
 $ tBodyAcc.arCoeff...Z.3              : num  0.4919 -0.0167 0.1739 0.4821 0.1794 ...
 $ tBodyAcc.arCoeff...Z.4              : num  -0.191 -0.221 -0.299 -0.47 -0.089 ...
 $ tBodyAcc.correlation...X.Y          : num  0.3763 -0.0134 -0.1247 -0.3057 -0.1558 ...
 $ tBodyAcc.correlation...X.Z          : num  0.4351 -0.0727 -0.1811 -0.3627 -0.1898 ...
 $ tBodyAcc.correlation...Y.Z          : num  0.661 0.579 0.609 0.507 0.599 ...
 $ tGravityAcc.mean...X                : num  0.963 0.967 0.967 0.968 0.968 ...
 $ tGravityAcc.mean...Y                : num  -0.141 -0.142 -0.142 -0.144 -0.149 ...
 $ tGravityAcc.mean...Z                : num  0.1154 0.1094 0.1019 0.0999 0.0945 ...
 $ tGravityAcc.std...X                 : num  -0.985 -0.997 -1 -0.997 -0.998 ...
 $ tGravityAcc.std...Y                 : num  -0.982 -0.989 -0.993 -0.981 -0.988 ...
 $ tGravityAcc.std...Z                 : num  -0.878 -0.932 -0.993 -0.978 -0.979 ...
 $ tGravityAcc.mad...X                 : num  -0.985 -0.998 -1 -0.996 -0.998 ...
 $ tGravityAcc.mad...Y                 : num  -0.984 -0.99 -0.993 -0.981 -0.989 ...
 $ tGravityAcc.mad...Z                 : num  -0.895 -0.933 -0.993 -0.978 -0.979 ...
 $ tGravityAcc.max...X                 : num  0.892 0.892 0.892 0.894 0.894 ...
 $ tGravityAcc.max...Y                 : num  -0.161 -0.161 -0.164 -0.164 -0.167 ...
 $ tGravityAcc.max...Z                 : num  0.1247 0.1226 0.0946 0.0934 0.0917 ...
 $ tGravityAcc.min...X                 : num  0.977 0.985 0.987 0.987 0.987 ...
 $ tGravityAcc.min...Y                 : num  -0.123 -0.115 -0.115 -0.121 -0.122 ...
 $ tGravityAcc.min...Z                 : num  0.0565 0.1028 0.1028 0.0958 0.0941 ...
 $ tGravityAcc.sma..                   : num  -0.375 -0.383 -0.402 -0.4 -0.4 ...
 $ tGravityAcc.energy...X              : num  0.899 0.908 0.909 0.911 0.912 ...
 $ tGravityAcc.energy...Y              : num  -0.971 -0.971 -0.97 -0.969 -0.967 ...
 $ tGravityAcc.energy...Z              : num  -0.976 -0.979 -0.982 -0.982 -0.984 ...
 $ tGravityAcc.iqr...X                 : num  -0.984 -0.999 -1 -0.996 -0.998 ...
 $ tGravityAcc.iqr...Y                 : num  -0.989 -0.99 -0.992 -0.981 -0.991 ...
 $ tGravityAcc.iqr...Z                 : num  -0.918 -0.942 -0.993 -0.98 -0.98 ...
 $ tGravityAcc.entropy...X             : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
 $ tGravityAcc.entropy...Y             : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
 $ tGravityAcc.entropy...Z             : num  0.114 -0.21 -0.927 -0.596 -0.617 ...
 $ tGravityAcc.arCoeff...X.1           : num  -0.59042 -0.41006 0.00223 -0.06493 -0.25727 ...
 $ tGravityAcc.arCoeff...X.2           : num  0.5911 0.4139 0.0275 0.0754 0.2689 ...
 $ tGravityAcc.arCoeff...X.3           : num  -0.5918 -0.4176 -0.0567 -0.0858 -0.2807 ...
 $ tGravityAcc.arCoeff...X.4           : num  0.5925 0.4213 0.0855 0.0962 0.2926 ...
 $ tGravityAcc.arCoeff...Y.1           : num  -0.745 -0.196 -0.329 -0.295 -0.167 ...
 $ tGravityAcc.arCoeff...Y.2           : num  0.7209 0.1253 0.2705 0.2283 0.0899 ...
 $ tGravityAcc.arCoeff...Y.3           : num  -0.7124 -0.1056 -0.2545 -0.2063 -0.0663 ...
 $ tGravityAcc.arCoeff...Y.4           : num  0.7113 0.1091 0.2576 0.2048 0.0671 ...
 $ tGravityAcc.arCoeff...Z.1           : num  -0.995 -0.834 -0.705 -0.385 -0.237 ...
 $ tGravityAcc.arCoeff...Z.2           : num  0.996 0.834 0.714 0.386 0.239 ...
 $ tGravityAcc.arCoeff...Z.3           : num  -0.996 -0.834 -0.723 -0.387 -0.241 ...
 $ tGravityAcc.arCoeff...Z.4           : num  0.992 0.83 0.729 0.385 0.241 ...
 $ tGravityAcc.correlation...X.Y       : num  0.57 -0.831 -0.181 -0.991 -0.408 ...
 $ tGravityAcc.correlation...X.Z       : num  0.439 -0.866 0.338 -0.969 -0.185 ...
 $ tGravityAcc.correlation...Y.Z       : num  0.987 0.974 0.643 0.984 0.965 ...
 $ tBodyAccJerk.mean...X               : num  0.078 0.074 0.0736 0.0773 0.0734 ...
 $ tBodyAccJerk.mean...Y               : num  0.005 0.00577 0.0031 0.02006 0.01912 ...
 $ tBodyAccJerk.mean...Z               : num  -0.06783 0.02938 -0.00905 -0.00986 0.01678 ...
 $ tBodyAccJerk.std...X                : num  -0.994 -0.996 -0.991 -0.993 -0.996 ...
 $ tBodyAccJerk.std...Y                : num  -0.988 -0.981 -0.981 -0.988 -0.988 ...
 $ tBodyAccJerk.std...Z                : num  -0.994 -0.992 -0.99 -0.993 -0.992 ...
 $ tBodyAccJerk.mad...X                : num  -0.994 -0.996 -0.991 -0.994 -0.997 ...
 $ tBodyAccJerk.mad...Y                : num  -0.986 -0.979 -0.979 -0.986 -0.987 ...
 $ tBodyAccJerk.mad...Z                : num  -0.993 -0.991 -0.987 -0.991 -0.991 ...
 $ tBodyAccJerk.max...X                : num  -0.985 -0.995 -0.987 -0.987 -0.997 ...
 $ tBodyAccJerk.max...Y                : num  -0.992 -0.979 -0.979 -0.992 -0.992 ...
 $ tBodyAccJerk.max...Z                : num  -0.993 -0.992 -0.992 -0.99 -0.99 ...
 $ tBodyAccJerk.min...X                : num  0.99 0.993 0.988 0.988 0.994 ...
 $ tBodyAccJerk.min...Y                : num  0.992 0.992 0.992 0.993 0.993 ...
 $ tBodyAccJerk.min...Z                : num  0.991 0.989 0.989 0.993 0.986 ...
 $ tBodyAccJerk.sma..                  : num  -0.994 -0.991 -0.988 -0.993 -0.994 ...
 $ tBodyAccJerk.energy...X             : num  -1 -1 -1 -1 -1 ...
 $ tBodyAccJerk.energy...Y             : num  -1 -1 -1 -1 -1 ...
 $ tBodyAccJerk.energy...Z             : num  -1 -1 -1 -1 -1 ...
 $ tBodyAccJerk.iqr...X                : num  -0.994 -0.994 -0.988 -0.995 -0.996 ...
 $ tBodyAccJerk.iqr...Y                : num  -0.986 -0.979 -0.98 -0.987 -0.987 ...
 $ tBodyAccJerk.iqr...Z                : num  -0.989 -0.993 -0.982 -0.989 -0.991 ...
 $ tBodyAccJerk.entropy...X            : num  -0.82 -0.875 -0.754 -0.821 -0.851 ...
 $ tBodyAccJerk.entropy...Y            : num  -0.793 -0.655 -0.673 -0.755 -0.746 ...
 $ tBodyAccJerk.entropy...Z            : num  -0.889 -0.767 -0.747 -0.825 -0.797 ...
 $ tBodyAccJerk.arCoeff...X.1          : num  1 0.49 0.265 0.123 0.241 ...
 $ tBodyAccJerk.arCoeff...X.2          : num  -0.221 0.071 0.188 0.276 0.135 ...
 $ tBodyAccJerk.arCoeff...X.3          : num  0.637 0.363 0.465 0.457 0.297 ...
 $ tBodyAccJerk.arCoeff...X.4          : num  0.388 0.527 0.372 0.193 0.287 ...
 $ tBodyAccJerk.arCoeff...Y.1          : num  0.2414 0.1494 0.0827 0.1024 0.319 ...
 $ tBodyAccJerk.arCoeff...Y.2          : num  -0.05225 0.06293 -0.00462 -0.0991 -0.14336 ...
 $ tBodyAccJerk.arCoeff...Y.3          : num  0.264 0.37 0.327 0.195 0.477 ...
 $ tBodyAccJerk.arCoeff...Y.4          : num  0.373 0.414 0.438 0.484 0.418 ...
 $ tBodyAccJerk.arCoeff...Z.1          : num  0.342 0.122 0.258 0.358 0.39 ...
 $ tBodyAccJerk.arCoeff...Z.2          : num  -0.5698 0.1806 0.07 -0.187 -0.0303 ...
 $ tBodyAccJerk.arCoeff...Z.3          : num  0.2654 0.0474 0.187 0.2981 0.1633 ...
 $ tBodyAccJerk.arCoeff...Z.4          : num  -0.478 0.167 0.247 0.452 0.18 ...
 $ tBodyAccJerk.correlation...X.Y      : num  -0.385 -0.209 -0.12 -0.127 -0.273 ...
 $ tBodyAccJerk.correlation...X.Z      : num  0.0336 0.0841 -0.11 -0.0833 0.1031 ...
 $ tBodyAccJerk.correlation...Y.Z      : num  -0.1265 -0.2686 -0.04 0.4571 0.0647 ...
 $ tBodyGyro.mean...X                  : num  -0.0061 -0.0161 -0.0317 -0.0434 -0.034 ...
 $ tBodyGyro.mean...Y                  : num  -0.0314 -0.0839 -0.1023 -0.0914 -0.0747 ...
 $ tBodyGyro.mean...Z                  : num  0.1077 0.1006 0.0961 0.0855 0.0774 ...
 $ tBodyGyro.std...X                   : num  -0.985 -0.983 -0.976 -0.991 -0.985 ...
 $ tBodyGyro.std...Y                   : num  -0.977 -0.989 -0.994 -0.992 -0.992 ...
 $ tBodyGyro.std...Z                   : num  -0.992 -0.989 -0.986 -0.988 -0.987 ...
 $ tBodyGyro.mad...X                   : num  -0.985 -0.987 -0.975 -0.992 -0.987 ...
 $ tBodyGyro.mad...Y                   : num  -0.976 -0.989 -0.994 -0.993 -0.993 ...
 $ tBodyGyro.mad...Z                   : num  -0.992 -0.989 -0.986 -0.99 -0.988 ...
 $ tBodyGyro.max...X                   : num  -0.867 -0.865 -0.865 -0.885 -0.87 ...
 $ tBodyGyro.max...Y                   : num  -0.934 -0.954 -0.959 -0.957 -0.953 ...
 $ tBodyGyro.max...Z                   : num  -0.748 -0.746 -0.743 -0.743 -0.75 ...
 $ tBodyGyro.min...X                   : num  0.847 0.834 0.834 0.834 0.839 ...
 $ tBodyGyro.min...Y                   : num  0.915 0.908 0.906 0.906 0.911 ...
 $ tBodyGyro.min...Z                   : num  0.831 0.829 0.829 0.827 0.821 ...
 $ tBodyGyro.sma..                     : num  -0.967 -0.981 -0.976 -0.982 -0.985 ...
 $ tBodyGyro.energy...X                : num  -1 -1 -1 -1 -1 ...
 $ tBodyGyro.energy...Y                : num  -0.999 -1 -1 -1 -1 ...
 $ tBodyGyro.energy...Z                : num  -1 -1 -1 -1 -1 ...
 $ tBodyGyro.iqr...X                   : num  -0.983 -0.993 -0.972 -0.991 -0.99 ...
 $ tBodyGyro.iqr...Y                   : num  -0.979 -0.989 -0.995 -0.994 -0.993 ...
 $ tBodyGyro.iqr...Z                   : num  -0.993 -0.99 -0.987 -0.995 -0.991 ...
 $ tBodyGyro.entropy...X               : num  0.08263 0.00747 -0.26094 -0.93055 -0.62886 ...
 $ tBodyGyro.entropy...Y               : num  0.202 -0.531 -1 -0.827 -0.468 ...
 $ tBodyGyro.entropy...Z               : num  -0.169 -0.177 -0.248 -0.543 -0.651 ...
 $ tBodyGyro.arCoeff...X.1             : num  0.0963 -0.3877 -0.4372 -0.1659 -0.2127 ...
 $ tBodyGyro.arCoeff...X.2             : num  -0.27499 0.17914 0.23898 -0.01288 0.00211 ...
 $ tBodyGyro.arCoeff...X.3             : num  0.499 0.211 0.145 0.32 0.388 ...
 $ tBodyGyro.arCoeff...X.4             : num  -0.22 -0.14 -0.114 -0.165 -0.233 ...
 $ tBodyGyro.arCoeff...Y.1             : num  1 -0.047 0.0323 0.0446 -0.1632 ...
 $ tBodyGyro.arCoeff...Y.2             : num  -0.973 -0.0649 -0.1279 -0.1252 0.1865 ...
 $ tBodyGyro.arCoeff...Y.3             : num  0.3167 0.1177 0.1149 0.0783 -0.4349 ...
 $ tBodyGyro.arCoeff...Y.4             : num  0.3757 0.0817 0.1254 0.177 0.6501 ...
 $ tBodyGyro.arCoeff...Z.1             : num  0.7234 0.0424 0.1121 0.1934 0.24 ...
 $ tBodyGyro.arCoeff...Z.2             : num  -0.771 -0.15 -0.166 -0.207 -0.34 ...
 $ tBodyGyro.arCoeff...Z.3             : num  0.69 0.293 0.135 0.112 0.133 ...
 $ tBodyGyro.arCoeff...Z.4             : num  -0.332 -0.149 0.184 0.202 0.473 ...
 $ tBodyGyro.correlation...X.Y         : num  0.7096 0.0467 -0.0101 0.2102 -0.142 ...
 $ tBodyGyro.correlation...X.Z         : num  0.1349 -0.2569 0.0433 0.1411 0.4844 ...
 $ tBodyGyro.correlation...Y.Z         : num  0.301 0.169 -0.351 -0.725 -0.725 ...
 $ tBodyGyroJerk.mean...X              : num  -0.0992 -0.1105 -0.1085 -0.0912 -0.0908 ...
 $ tBodyGyroJerk.mean...Y              : num  -0.0555 -0.0448 -0.0424 -0.0363 -0.0376 ...
 $ tBodyGyroJerk.mean...Z              : num  -0.062 -0.0592 -0.0558 -0.0605 -0.0583 ...
 $ tBodyGyroJerk.std...X               : num  -0.992 -0.99 -0.988 -0.991 -0.991 ...
 $ tBodyGyroJerk.std...Y               : num  -0.993 -0.997 -0.996 -0.997 -0.996 ...
 $ tBodyGyroJerk.std...Z               : num  -0.992 -0.994 -0.992 -0.993 -0.995 ...
 $ tBodyGyroJerk.mad...X               : num  -0.992 -0.99 -0.988 -0.991 -0.993 ...
 $ tBodyGyroJerk.mad...Y               : num  -0.995 -0.997 -0.996 -0.997 -0.997 ...
 $ tBodyGyroJerk.mad...Z               : num  -0.993 -0.994 -0.992 -0.994 -0.994 ...
 $ tBodyGyroJerk.max...X               : num  -0.99 -0.992 -0.993 -0.994 -0.98 ...
 $ tBodyGyroJerk.max...Y               : num  -0.987 -0.998 -0.994 -0.994 -0.998 ...
 $ tBodyGyroJerk.max...Z               : num  -0.992 -0.995 -0.989 -0.989 -0.993 ...
 $ tBodyGyroJerk.min...X               : num  0.994 0.99 0.989 0.989 0.994 ...
 $ tBodyGyroJerk.min...Y               : num  0.992 0.997 0.997 0.998 0.997 ...
 $ tBodyGyroJerk.min...Z               : num  0.989 0.995 0.994 0.994 0.997 ...
 $ tBodyGyroJerk.sma..                 : num  -0.994 -0.995 -0.993 -0.995 -0.996 ...
 $ tBodyGyroJerk.energy...X            : num  -1 -1 -1 -1 -1 ...
 $ tBodyGyroJerk.energy...Y            : num  -1 -1 -1 -1 -1 ...
 $ tBodyGyroJerk.energy...Z            : num  -1 -1 -1 -1 -1 ...
 $ tBodyGyroJerk.iqr...X               : num  -0.992 -0.991 -0.987 -0.991 -0.995 ...
 $ tBodyGyroJerk.iqr...Y               : num  -0.997 -0.997 -0.995 -0.997 -0.997 ...
 $ tBodyGyroJerk.iqr...Z               : num  -0.992 -0.994 -0.993 -0.995 -0.994 ...
 $ tBodyGyroJerk.entropy...X           : num  -0.59 -0.601 -0.544 -0.562 -0.618 ...
 $ tBodyGyroJerk.entropy...Y           : num  -0.688 -0.748 -0.673 -0.731 -0.683 ...
 $ tBodyGyroJerk.entropy...Z           : num  -0.572 -0.609 -0.588 -0.661 -0.633 ...
 $ tBodyGyroJerk.arCoeff...X.1         : num  0.29238 -0.19331 -0.24115 0.00989 -0.02568 ...
 $ tBodyGyroJerk.arCoeff...X.2         : num  -0.362 -0.0674 -0.0114 -0.1376 -0.1881 ...
 $ tBodyGyroJerk.arCoeff...X.3         : num  0.406 0.186 0.116 0.126 0.231 ...
 $ tBodyGyroJerk.arCoeff...X.4         : num  -0.039 0.0415 0.0896 0.3161 0.2003 ...
 $ tBodyGyroJerk.arCoeff...Y.1         : num  0.9893 0.0724 0.096 0.0943 -0.1494 ...
 $ tBodyGyroJerk.arCoeff...Y.2         : num  -0.4146 -0.0354 0.0096 0.0262 0.272 ...
 $ tBodyGyroJerk.arCoeff...Y.3         : num  0.3916 0.1776 0.0951 0.0697 -0.2715 ...
 $ tBodyGyroJerk.arCoeff...Y.4         : num  0.28225 0.0275 0.25289 0.24665 -0.00994 ...
 $ tBodyGyroJerk.arCoeff...Z.1         : num  0.927 0.183 0.182 0.257 0.235 ...
 $ tBodyGyroJerk.arCoeff...Z.2         : num  -0.572 -0.167 -0.169 -0.137 -0.341 ...
 $ tBodyGyroJerk.arCoeff...Z.3         : num  0.6916 0.2533 0.132 0.0873 -0.0857 ...
 $ tBodyGyroJerk.arCoeff...Z.4         : num  0.4683 0.1323 0.0082 0.1491 0.164 ...
 $ tBodyGyroJerk.correlation...X.Y     : num  -0.131 0.294 0.193 0.197 0.121 ...
 $ tBodyGyroJerk.correlation...X.Z     : num  -0.0872 -0.0181 0.0737 0.1405 0.1075 ...
 $ tBodyGyroJerk.correlation...Y.Z     : num  0.336 -0.343 -0.315 -0.306 -0.283 ...
 $ tBodyAccMag.mean..                  : num  -0.959 -0.979 -0.984 -0.987 -0.993 ...
 $ tBodyAccMag.std..                   : num  -0.951 -0.976 -0.988 -0.986 -0.991 ...
 $ tBodyAccMag.mad..                   : num  -0.958 -0.978 -0.988 -0.986 -0.991 ...
 $ tBodyAccMag.max..                   : num  -0.946 -0.979 -0.986 -0.986 -0.991 ...
 $ tBodyAccMag.min..                   : num  -0.993 -0.995 -0.995 -0.997 -0.997 ...
 $ tBodyAccMag.sma..                   : num  -0.959 -0.979 -0.984 -0.987 -0.993 ...
 $ tBodyAccMag.energy..                : num  -0.998 -0.999 -1 -1 -1 ...
 $ tBodyAccMag.iqr..                   : num  -0.958 -0.981 -0.986 -0.984 -0.99 ...
 $ tBodyAccMag.entropy..               : num  -0.233 -0.442 -0.6 -0.589 -0.705 ...
 $ tBodyAccMag.arCoeff..1              : num  -0.1732 0.0816 0.038 -0.0929 0.1804 ...
 $ tBodyAccMag.arCoeff..2              : num  -0.0229 -0.1094 -0.0742 0.0464 -0.2777 ...
 $ tBodyAccMag.arCoeff..3              : num  0.094832 0.311758 0.254076 -0.000466 0.515562 ...
 $ tBodyAccMag.arCoeff..4              : num  0.1918 -0.4117 -0.2961 0.0371 -0.3559 ...
 $ tGravityAccMag.mean..               : num  -0.959 -0.979 -0.984 -0.987 -0.993 ...
 $ tGravityAccMag.std..                : num  -0.951 -0.976 -0.988 -0.986 -0.991 ...
 $ tGravityAccMag.mad..                : num  -0.958 -0.978 -0.988 -0.986 -0.991 ...
 $ tGravityAccMag.max..                : num  -0.946 -0.979 -0.986 -0.986 -0.991 ...
 $ tGravityAccMag.min..                : num  -0.993 -0.995 -0.995 -0.997 -0.997 ...
 $ tGravityAccMag.sma..                : num  -0.959 -0.979 -0.984 -0.987 -0.993 ...
 $ tGravityAccMag.energy..             : num  -0.998 -0.999 -1 -1 -1 ...
 $ tGravityAccMag.iqr..                : num  -0.958 -0.981 -0.986 -0.984 -0.99 ...
 $ tGravityAccMag.entropy..            : num  -0.233 -0.442 -0.6 -0.589 -0.705 ...
 $ tGravityAccMag.arCoeff..1           : num  -0.1732 0.0816 0.038 -0.0929 0.1804 ...
 $ tGravityAccMag.arCoeff..2           : num  -0.0229 -0.1094 -0.0742 0.0464 -0.2777 ...
 $ tGravityAccMag.arCoeff..3           : num  0.094832 0.311758 0.254076 -0.000466 0.515562 ...
 $ tGravityAccMag.arCoeff..4           : num  0.1918 -0.4117 -0.2961 0.0371 -0.3559 ...
 $ tBodyAccJerkMag.mean..              : num  -0.993 -0.991 -0.989 -0.993 -0.993 ...
 $ tBodyAccJerkMag.std..               : num  -0.994 -0.992 -0.99 -0.993 -0.996 ...
 $ tBodyAccJerkMag.mad..               : num  -0.995 -0.993 -0.991 -0.993 -0.996 ...
 $ tBodyAccJerkMag.max..               : num  -0.993 -0.989 -0.989 -0.993 -0.993 ...
 $ tBodyAccJerkMag.min..               : num  -0.991 -0.991 -0.993 -0.993 -0.981 ...
 $ tBodyAccJerkMag.sma..               : num  -0.993 -0.991 -0.989 -0.993 -0.993 ...
 $ tBodyAccJerkMag.energy..            : num  -1 -1 -1 -1 -1 ...
 $ tBodyAccJerkMag.iqr..               : num  -0.993 -0.993 -0.99 -0.992 -0.997 ...
 $ tBodyAccJerkMag.entropy..           : num  -0.863 -0.82 -0.795 -0.792 -0.85 ...
 $ tBodyAccJerkMag.arCoeff..1          : num  0.283 0.459 0.65 0.662 0.312 ...
 $ tBodyAccJerkMag.arCoeff..2          : num  -0.237 -0.245 -0.26 -0.247 -0.17 ...
 $ tBodyAccJerkMag.arCoeff..3          : num  -0.1054 0.0561 -0.1284 -0.2303 0.1344 ...
 $ tBodyAccJerkMag.arCoeff..4          : num  -0.0382 -0.4583 -0.5205 -0.4365 -0.4583 ...
 $ tBodyGyroMag.mean..                 : num  -0.969 -0.981 -0.976 -0.982 -0.985 ...
 $ tBodyGyroMag.std..                  : num  -0.964 -0.984 -0.986 -0.987 -0.989 ...
 $ tBodyGyroMag.mad..                  : num  -0.957 -0.982 -0.984 -0.986 -0.99 ...
 $ tBodyGyroMag.max..                  : num  -0.975 -0.985 -0.985 -0.99 -0.987 ...
 $ tBodyGyroMag.min..                  : num  -0.992 -0.992 -0.966 -0.982 -0.982 ...
 $ tBodyGyroMag.sma..                  : num  -0.969 -0.981 -0.976 -0.982 -0.985 ...
 $ tBodyGyroMag.energy..               : num  -0.999 -1 -1 -1 -1 ...
 $ tBodyGyroMag.iqr..                  : num  -0.95 -0.983 -0.983 -0.984 -0.992 ...
 $ tBodyGyroMag.entropy..              : num  0.0726 -0.1929 -0.2228 -0.2407 -0.3387 ...
 $ tBodyGyroMag.arCoeff..1             : num  0.573 -0.225 -0.227 -0.202 -0.237 ...
 $ tBodyGyroMag.arCoeff..2             : num  -0.7386 -0.0171 0.0597 0.0547 0.0938 ...
 $ tBodyGyroMag.arCoeff..3             : num  0.2126 0.1558 0.0615 0.1101 0.0233 ...
 $ tBodyGyroMag.arCoeff..4             : num  0.4334 0.0826 0.0417 -0.0794 0.039 ...
 $ tBodyGyroJerkMag.mean..             : num  -0.994 -0.995 -0.993 -0.996 -0.996 ...
 $ tBodyGyroJerkMag.std..              : num  -0.991 -0.996 -0.995 -0.995 -0.995 ...
 $ tBodyGyroJerkMag.mad..              : num  -0.993 -0.996 -0.995 -0.995 -0.996 ...
 $ tBodyGyroJerkMag.max..              : num  -0.989 -0.997 -0.995 -0.995 -0.992 ...
 $ tBodyGyroJerkMag.min..              : num  -0.993 -0.992 -0.998 -0.998 -0.992 ...
 $ tBodyGyroJerkMag.sma..              : num  -0.994 -0.995 -0.993 -0.996 -0.996 ...
 $ tBodyGyroJerkMag.energy..           : num  -1 -1 -1 -1 -1 ...
 $ tBodyGyroJerkMag.iqr..              : num  -0.995 -0.995 -0.994 -0.995 -0.996 ...
 $ tBodyGyroJerkMag.entropy..          : num  -0.62 -0.731 -0.663 -0.683 -0.72 ...
 $ tBodyGyroJerkMag.arCoeff..1         : num  0.293 0.209 0.328 0.595 0.332 ...
 $ tBodyGyroJerkMag.arCoeff..2         : num  -0.177 -0.178 -0.155 -0.265 -0.261 ...
 $ tBodyGyroJerkMag.arCoeff..3         : num  -0.146 -0.103 -0.221 -0.316 -0.146 ...
 $ tBodyGyroJerkMag.arCoeff..4         : num  -0.12407 -0.04382 -0.10751 -0.16383 -0.00737 ...
 $ fBodyAcc.mean...X                   : num  -0.995 -0.997 -0.994 -0.995 -0.997 ...
 $ fBodyAcc.mean...Y                   : num  -0.983 -0.977 -0.973 -0.984 -0.982 ...
 $ fBodyAcc.mean...Z                   : num  -0.939 -0.974 -0.983 -0.991 -0.988 ...
 $ fBodyAcc.std...X                    : num  -0.995 -0.999 -0.996 -0.996 -0.999 ...
 $ fBodyAcc.std...Y                    : num  -0.983 -0.975 -0.966 -0.983 -0.98 ...
 $ fBodyAcc.std...Z                    : num  -0.906 -0.955 -0.977 -0.99 -0.992 ...
 $ fBodyAcc.mad...X                    : num  -0.997 -0.998 -0.994 -0.995 -0.998 ...
 $ fBodyAcc.mad...Y                    : num  -0.985 -0.977 -0.972 -0.983 -0.982 ...
 $ fBodyAcc.mad...Z                    : num  -0.932 -0.968 -0.982 -0.989 -0.991 ...
 $ fBodyAcc.max...X                    : num  -0.994 -0.999 -0.998 -0.997 -0.999 ...
 $ fBodyAcc.max...Y                    : num  -0.983 -0.974 -0.963 -0.987 -0.981 ...
 $ fBodyAcc.max...Z                    : num  -0.885 -0.949 -0.969 -0.988 -0.989 ...
 $ fBodyAcc.min...X                    : num  -0.994 -0.998 -0.997 -0.994 -0.995 ...
 $ fBodyAcc.min...Y                    : num  -0.993 -0.993 -0.99 -0.99 -0.992 ...
 $ fBodyAcc.min...Z                    : num  -0.923 -0.99 -0.991 -0.997 -0.974 ...
 $ fBodyAcc.sma..                      : num  -0.975 -0.986 -0.986 -0.993 -0.992 ...
 $ fBodyAcc.energy...X                 : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.energy...Y                 : num  -1 -0.999 -0.999 -1 -1 ...
 $ fBodyAcc.energy...Z                 : num  -0.995 -0.999 -0.999 -1 -1 ...
 $ fBodyAcc.iqr...X                    : num  -0.996 -0.995 -0.989 -0.99 -0.994 ...
 $ fBodyAcc.iqr...Y                    : num  -0.99 -0.981 -0.977 -0.992 -0.988 ...
 $ fBodyAcc.iqr...Z                    : num  -0.988 -0.986 -0.981 -0.988 -0.986 ...
 $ fBodyAcc.entropy...X                : num  -0.946 -1 -1 -1 -1 ...
 $ fBodyAcc.entropy...Y                : num  -0.905 -0.905 -0.816 -0.87 -0.87 ...
 $ fBodyAcc.entropy...Z                : num  -0.591 -0.758 -0.814 -0.944 -0.944 ...
 $ fBodyAcc.maxInds.X                  : num  -1 0.0968 -0.9355 -1 0.0968 ...
 $ fBodyAcc.maxInds.Y                  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.maxInds.Z                  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.meanFreq...X               : num  0.252 0.271 0.125 0.029 0.181 ...
 $ fBodyAcc.meanFreq...Y               : num  0.1318 0.0429 -0.0646 0.0803 0.058 ...
 $ fBodyAcc.meanFreq...Z               : num  -0.0521 -0.0143 0.0827 0.1857 0.5598 ...
 $ fBodyAcc.skewness...X               : num  0.142 -0.693 -0.727 -0.599 -0.677 ...
 $ fBodyAcc.kurtosis...X               : num  -0.151 -0.954 -0.965 -0.908 -0.951 ...
 $ fBodyAcc.skewness...Y               : num  -0.2205 -0.0497 0.1631 -0.4609 -0.1804 ...
 $ fBodyAcc.kurtosis...Y               : num  -0.5587 -0.332 -0.0922 -0.8131 -0.5337 ...
 $ fBodyAcc.skewness...Z               : num  0.2468 0.0567 -0.0449 -0.5668 -0.5855 ...
 $ fBodyAcc.kurtosis...Z               : num  -0.00742 -0.289 -0.28837 -0.77125 -0.79043 ...
 $ fBodyAcc.bandsEnergy...1.8          : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...9.16         : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...17.24        : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...25.32        : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...33.40        : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...41.48        : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...49.56        : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...57.64        : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...1.16         : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...17.32        : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...33.48        : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...49.64        : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...1.24         : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...25.48        : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...1.8.1        : num  -1 -0.999 -0.999 -1 -1 ...
 $ fBodyAcc.bandsEnergy...9.16.1       : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...17.24.1      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...25.32.1      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...33.40.1      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...41.48.1      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...49.56.1      : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...57.64.1      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...1.16.1       : num  -1 -0.999 -0.999 -1 -1 ...
 $ fBodyAcc.bandsEnergy...17.32.1      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...33.48.1      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...49.64.1      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...1.24.1       : num  -1 -0.999 -0.999 -1 -1 ...
 $ fBodyAcc.bandsEnergy...25.48.1      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...1.8.2        : num  -0.994 -0.998 -0.999 -1 -1 ...
 $ fBodyAcc.bandsEnergy...9.16.2       : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...17.24.2      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...25.32.2      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...33.40.2      : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...41.48.2      : num  -0.998 -0.999 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...49.56.2      : num  -0.996 -0.999 -1 -1 -0.999 ...
 $ fBodyAcc.bandsEnergy...57.64.2      : num  -0.995 -0.999 -1 -1 -0.999 ...
 $ fBodyAcc.bandsEnergy...1.16.2       : num  -0.995 -0.999 -0.999 -1 -1 ...
 $ fBodyAcc.bandsEnergy...17.32.2      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...33.48.2      : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyAcc.bandsEnergy...49.64.2      : num  -0.996 -0.999 -1 -1 -0.999 ...
 $ fBodyAcc.bandsEnergy...1.24.2       : num  -0.995 -0.999 -0.999 -1 -1 ...
 $ fBodyAcc.bandsEnergy...25.48.2      : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyAccJerk.mean...X               : num  -0.992 -0.995 -0.991 -0.994 -0.996 ...
 $ fBodyAccJerk.mean...Y               : num  -0.987 -0.981 -0.982 -0.989 -0.989 ...
 $ fBodyAccJerk.mean...Z               : num  -0.99 -0.99 -0.988 -0.991 -0.991 ...
 $ fBodyAccJerk.std...X                : num  -0.996 -0.997 -0.991 -0.991 -0.997 ...
 $ fBodyAccJerk.std...Y                : num  -0.991 -0.982 -0.981 -0.987 -0.989 ...
 $ fBodyAccJerk.std...Z                : num  -0.997 -0.993 -0.99 -0.994 -0.993 ...
 $ fBodyAccJerk.mad...X                : num  -0.994 -0.995 -0.988 -0.989 -0.996 ...
 $ fBodyAccJerk.mad...Y                : num  -0.991 -0.983 -0.981 -0.987 -0.989 ...
 $ fBodyAccJerk.mad...Z                : num  -0.997 -0.992 -0.988 -0.994 -0.992 ...
 $ fBodyAccJerk.max...X                : num  -0.997 -0.997 -0.995 -0.993 -0.997 ...
 $ fBodyAccJerk.max...Y                : num  -0.992 -0.985 -0.985 -0.988 -0.99 ...
 $ fBodyAccJerk.max...Z                : num  -0.993 -0.993 -0.994 -0.994 -0.995 ...
 $ fBodyAccJerk.min...X                : num  -0.998 -0.998 -0.997 -0.998 -0.996 ...
 $ fBodyAccJerk.min...Y                : num  -0.991 -0.983 -0.999 -1 -0.996 ...
 $ fBodyAccJerk.min...Z                : num  -0.96 -0.987 -0.998 -0.965 -0.996 ...
 $ fBodyAccJerk.sma..                  : num  -0.991 -0.99 -0.987 -0.993 -0.993 ...
 $ fBodyAccJerk.energy...X             : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.energy...Y             : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.energy...Z             : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.iqr...X                : num  -0.993 -0.993 -0.982 -0.992 -0.996 ...
 $ fBodyAccJerk.iqr...Y                : num  -0.991 -0.985 -0.985 -0.991 -0.992 ...
 $ fBodyAccJerk.iqr...Z                : num  -0.996 -0.991 -0.982 -0.993 -0.986 ...
 $ fBodyAccJerk.entropy...X            : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.entropy...Y            : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.entropy...Z            : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.maxInds.X              : num  1 -0.32 -0.16 -0.12 -0.32 -0.32 -0.12 -0.2 -0.2 0.12 ...
 $ fBodyAccJerk.maxInds.Y              : num  -0.24 -0.12 -0.48 -0.56 -0.08 -0.36 -0.6 -0.48 0.2 -0.56 ...
 $ fBodyAccJerk.maxInds.Z              : num  -1 -0.32 -0.28 -0.28 0.04 0.52 0 -0.04 -0.04 -0.08 ...
 $ fBodyAccJerk.meanFreq...X           : num  0.8704 0.6085 0.1154 0.0358 0.2734 ...
 $ fBodyAccJerk.meanFreq...Y           : num  0.2107 -0.0537 -0.1934 -0.093 0.0791 ...
 $ fBodyAccJerk.meanFreq...Z           : num  0.2637 0.0631 0.0383 0.1681 0.2924 ...
 $ fBodyAccJerk.skewness...X           : num  -0.704 -0.63 -0.595 -0.264 -0.522 ...
 $ fBodyAccJerk.kurtosis...X           : num  -0.904 -0.91 -0.924 -0.757 -0.813 ...
 $ fBodyAccJerk.skewness...Y           : num  -0.583 -0.414 -0.529 -0.396 -0.497 ...
 $ fBodyAccJerk.kurtosis...Y           : num  -0.936 -0.851 -0.913 -0.83 -0.904 ...
 $ fBodyAccJerk.skewness...Z           : num  -0.507 -0.656 -0.803 -0.577 -0.764 ...
 $ fBodyAccJerk.kurtosis...Z           : num  -0.806 -0.916 -0.98 -0.893 -0.966 ...
 $ fBodyAccJerk.bandsEnergy...1.8      : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...9.16     : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...17.24    : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...25.32    : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...33.40    : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...41.48    : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...49.56    : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...57.64    : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...1.16     : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...17.32    : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...33.48    : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...49.64    : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...1.24     : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...25.48    : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...1.8.1    : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...9.16.1   : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...17.24.1  : num  -1 -0.999 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...25.32.1  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...33.40.1  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...41.48.1  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...49.56.1  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...57.64.1  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...1.16.1   : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...17.32.1  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...33.48.1  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...49.64.1  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...1.24.1   : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...25.48.1  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...1.8.2    : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...9.16.2   : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...17.24.2  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...25.32.2  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...33.40.2  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...41.48.2  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...49.56.2  : num  -0.999 -1 -0.999 -0.999 -0.999 ...
 $ fBodyAccJerk.bandsEnergy...57.64.2  : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...1.16.2   : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...17.32.2  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...33.48.2  : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...49.64.2  : num  -0.999 -1 -1 -0.999 -0.999 ...
 $ fBodyAccJerk.bandsEnergy...1.24.2   : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccJerk.bandsEnergy...25.48.2  : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.mean...X                  : num  -0.987 -0.977 -0.975 -0.987 -0.982 ...
 $ fBodyGyro.mean...Y                  : num  -0.982 -0.993 -0.994 -0.994 -0.993 ...
 $ fBodyGyro.mean...Z                  : num  -0.99 -0.99 -0.987 -0.987 -0.989 ...
 $ fBodyGyro.std...X                   : num  -0.985 -0.985 -0.977 -0.993 -0.986 ...
 $ fBodyGyro.std...Y                   : num  -0.974 -0.987 -0.993 -0.992 -0.992 ...
 $ fBodyGyro.std...Z                   : num  -0.994 -0.99 -0.987 -0.989 -0.988 ...
 $ fBodyGyro.mad...X                   : num  -0.987 -0.979 -0.976 -0.99 -0.983 ...
 $ fBodyGyro.mad...Y                   : num  -0.984 -0.992 -0.994 -0.993 -0.993 ...
 $ fBodyGyro.mad...Z                   : num  -0.992 -0.988 -0.985 -0.987 -0.986 ...
 $ fBodyGyro.max...X                   : num  -0.98 -0.987 -0.973 -0.995 -0.988 ...
 $ fBodyGyro.max...Y                   : num  -0.972 -0.985 -0.995 -0.992 -0.993 ...
 $ fBodyGyro.max...Z                   : num  -0.995 -0.99 -0.991 -0.992 -0.991 ...
 $ fBodyGyro.min...X                   : num  -0.998 -0.987 -0.988 -0.99 -0.994 ...
 $ fBodyGyro.min...Y                   : num  -0.984 -0.999 -0.997 -0.994 -0.994 ...
 $ fBodyGyro.min...Z                   : num  -0.994 -0.994 -0.994 -0.993 -0.995 ...
 $ fBodyGyro.sma..                     : num  -0.985 -0.987 -0.986 -0.99 -0.989 ...
 $ fBodyGyro.energy...X                : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.energy...Y                : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.energy...Z                : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.iqr...X                   : num  -0.99 -0.987 -0.986 -0.993 -0.99 ...
 $ fBodyGyro.iqr...Y                   : num  -0.995 -0.996 -0.995 -0.996 -0.996 ...
 $ fBodyGyro.iqr...Z                   : num  -0.994 -0.987 -0.993 -0.99 -0.997 ...
 $ fBodyGyro.entropy...X               : num  -0.712 -0.611 -0.591 -0.724 -0.653 ...
 $ fBodyGyro.entropy...Y               : num  -0.645 -0.765 -0.808 -0.804 -0.827 ...
 $ fBodyGyro.entropy...Z               : num  -0.839 -0.751 -0.751 -0.817 -0.737 ...
 $ fBodyGyro.maxInds.X                 : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.maxInds.Y                 : num  -1 -1 -0.871 -1 -0.806 ...
 $ fBodyGyro.maxInds.Z                 : num  -1 -1 -1 -0.793 -1 ...
 $ fBodyGyro.meanFreq...X              : num  -0.2575 -0.0482 -0.2167 0.2169 -0.1533 ...
 $ fBodyGyro.meanFreq...Y              : num  0.0979 -0.4016 -0.0173 -0.1352 -0.0884 ...
 $ fBodyGyro.meanFreq...Z              : num  0.5472 -0.0682 -0.1107 -0.0497 -0.1622 ...
 $ fBodyGyro.skewness...X              : num  0.3773 -0.4586 0.0905 -0.5721 -0.3396 ...
 $ fBodyGyro.kurtosis...X              : num  0.134 -0.797 -0.245 -0.874 -0.723 ...
 $ fBodyGyro.skewness...Y              : num  0.273 0.388 -0.429 -0.135 -0.265 ...
 $ fBodyGyro.kurtosis...Y              : num  -0.0913 0.1487 -0.8126 -0.5422 -0.69 ...
 $ fBodyGyro.skewness...Z              : num  -0.484 -0.157 -0.392 -0.379 -0.268 ...
 $ fBodyGyro.kurtosis...Z              : num  -0.783 -0.452 -0.767 -0.757 -0.659 ...
 $ fBodyGyro.bandsEnergy...1.8         : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...9.16        : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...17.24       : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...25.32       : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...33.40       : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...41.48       : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...49.56       : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...57.64       : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...1.16        : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...17.32       : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...33.48       : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...49.64       : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...1.24        : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...25.48       : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...1.8.1       : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...9.16.1      : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...17.24.1     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...25.32.1     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...33.40.1     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...41.48.1     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...49.56.1     : num  -0.998 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...57.64.1     : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...1.16.1      : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...17.32.1     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...33.48.1     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...49.64.1     : num  -0.998 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...1.24.1      : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...25.48.1     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...1.8.2       : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...9.16.2      : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...17.24.2     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...25.32.2     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...33.40.2     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...41.48.2     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...49.56.2     : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...57.64.2     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...1.16.2      : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...17.32.2     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...33.48.2     : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...49.64.2     : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...1.24.2      : num  -1 -1 -1 -1 -1 ...
 $ fBodyGyro.bandsEnergy...25.48.2     : num  -1 -1 -1 -1 -1 ...
 $ fBodyAccMag.mean..                  : num  -0.952 -0.981 -0.988 -0.988 -0.994 ...
 $ fBodyAccMag.std..                   : num  -0.956 -0.976 -0.989 -0.987 -0.99 ...
 $ fBodyAccMag.mad..                   : num  -0.949 -0.976 -0.986 -0.984 -0.992 ...
 $ fBodyAccMag.max..                   : num  -0.974 -0.978 -0.993 -0.99 -0.991 ...
 $ fBodyAccMag.min..                   : num  -0.926 -0.987 -0.99 -0.998 -0.988 ...
 $ fBodyAccMag.sma..                   : num  -0.952 -0.981 -0.988 -0.988 -0.994 ...
 $ fBodyAccMag.energy..                : num  -0.998 -0.999 -1 -1 -1 ...
 $ fBodyAccMag.iqr..                   : num  -0.973 -0.984 -0.989 -0.983 -0.997 ...
 $ fBodyAccMag.entropy..               : num  -0.646 -0.817 -0.907 -0.907 -0.907 ...
 $ fBodyAccMag.maxInds                 : num  -0.793 -1 -0.862 -1 -1 ...
 $ fBodyAccMag.meanFreq..              : num  -0.0884 -0.0441 0.2579 0.0736 0.3943 ...
 $ fBodyAccMag.skewness..              : num  -0.436 -0.122 -0.619 -0.468 -0.113 ...
 $ fBodyAccMag.kurtosis..              : num  -0.797 -0.45 -0.88 -0.756 -0.482 ...
 $ fBodyBodyAccJerkMag.mean..          : num  -0.994 -0.99 -0.989 -0.993 -0.996 ...
 $ fBodyBodyAccJerkMag.std..           : num  -0.994 -0.992 -0.991 -0.992 -0.994 ...
 $ fBodyBodyAccJerkMag.mad..           : num  -0.992 -0.99 -0.987 -0.989 -0.993 ...
 $ fBodyBodyAccJerkMag.max..           : num  -0.993 -0.994 -0.993 -0.994 -0.995 ...
 $ fBodyBodyAccJerkMag.min..           : num  -0.988 -0.99 -1 -0.996 -0.982 ...
 $ fBodyBodyAccJerkMag.sma..           : num  -0.994 -0.99 -0.989 -0.993 -0.996 ...
 $ fBodyBodyAccJerkMag.energy..        : num  -1 -1 -1 -1 -1 ...
 $ fBodyBodyAccJerkMag.iqr..           : num  -0.991 -0.991 -0.987 -0.988 -0.994 ...
 $ fBodyBodyAccJerkMag.entropy..       : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
 $ fBodyBodyAccJerkMag.maxInds         : num  -0.937 -0.841 -0.905 1 -1 ...
 $ fBodyBodyAccJerkMag.meanFreq..      : num  0.347 0.532 0.661 0.679 0.559 ...
 $ fBodyBodyAccJerkMag.skewness..      : num  -0.516 -0.625 -0.725 -0.701 -0.529 ...
 $ fBodyBodyAccJerkMag.kurtosis..      : num  -0.803 -0.9 -0.929 -0.91 -0.859 ...
 $ fBodyBodyGyroMag.mean..             : num  -0.98 -0.988 -0.989 -0.989 -0.991 ...
 $ fBodyBodyGyroMag.std..              : num  -0.961 -0.983 -0.986 -0.988 -0.989 ...
 $ fBodyBodyGyroMag.mad..              : num  -0.974 -0.983 -0.984 -0.987 -0.988 ...
 $ fBodyBodyGyroMag.max..              : num  -0.952 -0.986 -0.991 -0.987 -0.991 ...
 $ fBodyBodyGyroMag.min..              : num  -0.989 -0.992 -0.996 -0.996 -0.998 ...
 $ fBodyBodyGyroMag.sma..              : num  -0.98 -0.988 -0.989 -0.989 -0.991 ...
 $ fBodyBodyGyroMag.energy..           : num  -0.999 -1 -1 -1 -1 ...
 $ fBodyBodyGyroMag.iqr..              : num  -0.993 -0.994 -0.993 -0.989 -0.989 ...
 $ fBodyBodyGyroMag.entropy..          : num  -0.701 -0.721 -0.737 -0.721 -0.763 ...
 $ fBodyBodyGyroMag.maxInds            : num  -1 -0.949 -0.795 -1 -0.897 ...
 $ fBodyBodyGyroMag.meanFreq..         : num  -0.129 -0.272 -0.2127 -0.0357 -0.2736 ...
 $ fBodyBodyGyroMag.skewness..         : num  0.586 -0.336 -0.535 -0.23 -0.51 ...
 $ fBodyBodyGyroMag.kurtosis..         : num  0.375 -0.72 -0.872 -0.511 -0.831 ...
 $ fBodyBodyGyroJerkMag.mean..         : num  -0.992 -0.996 -0.995 -0.995 -0.995 ...
 $ fBodyBodyGyroJerkMag.std..          : num  -0.991 -0.996 -0.995 -0.995 -0.995 ...
 $ fBodyBodyGyroJerkMag.mad..          : num  -0.99 -0.995 -0.995 -0.996 -0.995 ...
 $ fBodyBodyGyroJerkMag.max..          : num  -0.992 -0.997 -0.996 -0.995 -0.996 ...
 $ fBodyBodyGyroJerkMag.min..          : num  -0.991 -0.994 -0.996 -0.996 -0.997 ...
 $ fBodyBodyGyroJerkMag.sma..          : num  -0.992 -0.996 -0.995 -0.995 -0.995 ...
 $ fBodyBodyGyroJerkMag.energy..       : num  -1 -1 -1 -1 -1 ...
 $ fBodyBodyGyroJerkMag.iqr..          : num  -0.99 -0.995 -0.994 -0.995 -0.995 ...
 $ fBodyBodyGyroJerkMag.entropy..      : num  -0.871 -1 -1 -0.956 -1 ...
 $ fBodyBodyGyroJerkMag.maxInds        : num  -1 -1 -0.556 -0.937 -0.937 ...
 $ fBodyBodyGyroJerkMag.meanFreq..     : num  -0.0743 0.1581 0.4145 0.4046 0.0878 ...
 $ fBodyBodyGyroJerkMag.skewness..     : num  -0.299 -0.595 -0.391 -0.117 -0.351 ...
 $ fBodyBodyGyroJerkMag.kurtosis..     : num  -0.71 -0.861 -0.76 -0.483 -0.699 ...
 $ angle.tBodyAccMean.gravity.         : num  -0.1128 0.0535 -0.1186 -0.0368 0.1233 ...
 $ angle.tBodyAccJerkMean..gravityMean.: num  0.0304 -0.00743 0.1779 -0.01289 0.12254 ...
 $ angle.tBodyGyroMean.gravityMean.    : num  -0.465 -0.733 0.101 0.64 0.694 ...
 $ angle.tBodyGyroJerkMean.gravityMean.: num  -0.0184 0.7035 0.8085 -0.4854 -0.616 ...
 $ angle.X.gravityMean.                : num  -0.841 -0.845 -0.849 -0.849 -0.848 ...
 $ angle.Y.gravityMean.                : num  0.18 0.18 0.181 0.182 0.185 ...
 $ angle.Z.gravityMean.                : num  -0.0586 -0.0543 -0.0491 -0.0477 -0.0439 ...
 $ V1                                  : chr  "1" "1" "1" "1" ...
 $ V1                                  : chr  "5" "5" "5" "5" ...
----------------------------------------------------------------------------------------------   
```              
==============================================================================================         
| Results of the first Tidy data.frame.                                  
| Data extracted for the variables containing stand deviation and means.                                           
==============================================================================================         
| data.frame: xMeanStdData                                                           
==============================================================================================         
```                                                
str(xMeanStdData, list.len = 9999)                         
'data.frame':    10299 obs. of  563 variables:           
----------------------------------------------------------------------------------------------   
'data.frame':    10299 obs. of  68 variables:
 $ Subject.ID                 : num  7 5 6 23 7 7 11 6 10 11 ...
 $ Activity                   : chr  "WALKING" "WALKING" "WALKING" "WALKING" ...
 $ tBodyAcc.mean...X          : num  0.302 0.343 0.27 0.268 0.314 ...
 $ tBodyAcc.mean...Y          : num  -0.02688 -0.00343 0.01091 -0.01273 -0.0087 ...
 $ tBodyAcc.mean...Z          : num  -0.0958 -0.1015 -0.0749 -0.0937 -0.1246 ...
 $ tBodyAcc.std...X           : num  -0.38 -0.201 -0.337 -0.384 -0.356 ...
 $ tBodyAcc.std...Y           : num  -0.191 0.133 0.146 -0.204 -0.166 ...
 $ tBodyAcc.std...Z           : num  0.341 -0.318 -0.446 0.148 0.407 ...
 $ tGravityAcc.mean...X       : num  0.902 0.965 0.96 0.944 0.892 ...
 $ tGravityAcc.mean...Y       : num  -0.137 -0.145 -0.214 -0.159 -0.147 ...
 $ tGravityAcc.mean...Z       : num  -0.3428 0.0285 0.0505 -0.1425 -0.3414 ...
 $ tGravityAcc.std...X        : num  -0.953 -0.984 -0.965 -0.981 -0.98 ...
 $ tGravityAcc.std...Y        : num  -0.937 -0.953 -0.939 -0.973 -0.961 ...
 $ tGravityAcc.std...Z        : num  -0.921 -0.99 -0.946 -0.966 -0.941 ...
 $ tBodyAccJerk.mean...X      : num  0.1505 -0.1351 0.1262 -0.0358 -0.2256 ...
 $ tBodyAccJerk.mean...Y      : num  -0.2391 -0.0637 0.2083 -0.0136 -0.0699 ...
 $ tBodyAccJerk.mean...Z      : num  -0.1533 -0.2631 0.0773 0.2511 -0.0937 ...
 $ tBodyAccJerk.std...X       : num  -0.472 -0.197 -0.159 -0.333 -0.453 ...
 $ tBodyAccJerk.std...Y       : num  -0.1607 -0.0446 0.0551 -0.2088 -0.1215 ...
 $ tBodyAccJerk.std...Z       : num  -0.06331 -0.44016 -0.47746 -0.05011 -0.00443 ...
 $ tBodyGyro.mean...X         : num  0.2139 -0.0277 -0.0484 -0.0117 0.0334 ...
 $ tBodyGyro.mean...Y         : num  -0.049 -0.1253 -0.1036 -0.0135 -0.0969 ...
 $ tBodyGyro.mean...Z         : num  -0.24527 0.12289 0.08692 0.15683 -0.00968 ...
 $ tBodyGyro.std...X          : num  -0.512 -0.448 -0.407 -0.501 -0.536 ...
 $ tBodyGyro.std...Y          : num  -0.254 -0.394 -0.208 0.178 -0.239 ...
 $ tBodyGyro.std...Z          : num  -0.404 -0.311 -0.288 -0.305 -0.362 ...
 $ tBodyGyroJerk.mean...X     : num  -0.0634 0.0756 0.047 -0.1203 -0.203 ...
 $ tBodyGyroJerk.mean...Y     : num  0.03158 -0.05686 -0.09651 -0.00423 -0.16378 ...
 $ tBodyGyroJerk.mean...Z     : num  -0.0112 0.14377 0.00215 -0.18785 0.05743 ...
 $ tBodyGyroJerk.std...X      : num  -0.228 -0.3 -0.148 -0.411 -0.235 ...
 $ tBodyGyroJerk.std...Y      : num  -0.293 -0.454 -0.211 0.173 -0.279 ...
 $ tBodyGyroJerk.std...Z      : num  -0.56075 -0.09672 -0.00331 -0.44637 -0.55917 ...
 $ tBodyAccMag.mean..         : num  -0.0919 -0.0604 -0.1786 -0.1654 -0.0508 ...
 $ tBodyAccMag.std..          : num  -0.219 -0.318 -0.331 -0.25 -0.193 ...
 $ tGravityAccMag.mean..      : num  -0.0919 -0.0604 -0.1786 -0.1654 -0.0508 ...
 $ tGravityAccMag.std..       : num  -0.219 -0.318 -0.331 -0.25 -0.193 ...
 $ tBodyAccJerkMag.mean..     : num  -0.221 -0.177 -0.154 -0.165 -0.167 ...
 $ tBodyAccJerkMag.std..      : num  -0.0879 -0.1895 -0.1146 -0.0714 -0.0674 ...
 $ tBodyGyroMag.mean..        : num  -0.2319 -0.2911 -0.2321 -0.0934 -0.3111 ...
 $ tBodyGyroMag.std..         : num  -0.359 -0.457 -0.169 0.095 -0.26 ...
 $ tBodyGyroJerkMag.mean..    : num  -0.3526 -0.3462 -0.1846 -0.0862 -0.3425 ...
 $ tBodyGyroJerkMag.std..     : num  -0.26 -0.432 -0.175 0.135 -0.255 ...
 $ fBodyAcc.mean...X          : num  -0.426 -0.18 -0.229 -0.337 -0.377 ...
 $ fBodyAcc.mean...Y          : num  -0.0972 0.0852 0.1118 -0.1718 -0.1915 ...
 $ fBodyAcc.mean...Z          : num  0.1846 -0.3 -0.4013 0.0634 0.1929 ...
 $ fBodyAcc.std...X           : num  -0.363 -0.21 -0.384 -0.403 -0.347 ...
 $ fBodyAcc.std...Y           : num  -0.2983 0.0866 0.0919 -0.272 -0.2047 ...
 $ fBodyAcc.std...Z           : num  0.319 -0.385 -0.52 0.104 0.41 ...
 $ fBodyAccJerk.mean...X      : num  -0.49 -0.2 -0.174 -0.353 -0.466 ...
 $ fBodyAccJerk.mean...Y      : num  -0.189 -0.1399 -0.0781 -0.2802 -0.2017 ...
 $ fBodyAccJerk.mean...Z      : num  0.0147 -0.39925 -0.41452 -0.06667 0.00383 ...
 $ fBodyAccJerk.std...X       : num  -0.5 -0.269 -0.219 -0.372 -0.489 ...
 $ fBodyAccJerk.std...Y       : num  -0.18651 -0.00372 0.12855 -0.18274 -0.09159 ...
 $ fBodyAccJerk.std...Z       : num  -0.1381 -0.4783 -0.5398 -0.0346 -0.011 ...
 $ fBodyGyro.mean...X         : num  -0.321 -0.311 -0.164 -0.368 -0.347 ...
 $ fBodyGyro.mean...Y         : num  -0.201 -0.414 -0.185 0.127 -0.248 ...
 $ fBodyGyro.mean...Z         : num  -0.4485 -0.157 -0.0698 -0.2908 -0.4522 ...
 $ fBodyGyro.std...X          : num  -0.574 -0.491 -0.487 -0.544 -0.598 ...
 $ fBodyGyro.std...Y          : num  -0.294 -0.387 -0.229 0.201 -0.239 ...
 $ fBodyGyro.std...Z          : num  -0.445 -0.433 -0.441 -0.373 -0.393 ...
 $ fBodyAccMag.mean..         : num  -0.224 -0.196 -0.213 -0.135 -0.168 ...
 $ fBodyAccMag.std..          : num  -0.338 -0.505 -0.512 -0.44 -0.333 ...
 $ fBodyBodyAccJerkMag.mean.. : num  -0.1081 -0.1625 -0.0958 -0.0753 -0.081 ...
 $ fBodyBodyAccJerkMag.std..  : num  -0.0685 -0.2309 -0.139 -0.0728 -0.0562 ...
 $ fBodyBodyGyroMag.mean..    : num  -0.356 -0.414 -0.149 0.202 -0.255 ...
 $ fBodyBodyGyroMag.std..     : num  -0.474 -0.589 -0.331 -0.192 -0.394 ...
 $ fBodyBodyGyroJerkMag.mean..: num  -0.2935 -0.5085 -0.2354 0.0615 -0.2945 ...
 $ fBodyBodyGyroJerkMag.std.. : num  -0.269 -0.382 -0.158 0.149 -0.256 ...
```       
----------------------------------------------------------------------------------------------   

==============================================================================================         
| Results of the final Tidy data.frame.                                  
| Data summarized on Student.ID & Activity for 66 variables of stand deviation and means.                                           
==============================================================================================         
| data.frame: TidyDataSet                                                           
==============================================================================================         
```                                                
str(TidyDataSet, list.len = 9999)                         
'data.frame':    10299 obs. of  563 variables:           
----------------------------------------------------------------------------------------------   
'data.frame':    180 obs. of  68 variables:
 $ Subject.ID                 : num  1 1 1 1 1 1 2 2 2 2 ...
 $ Activity                   : chr  "LAYING" "SITTING" "STANDING" "WALKING" ...
 $ tBodyAcc.mean...X          : num  0.222 0.261 0.279 0.277 0.289 ...
 $ tBodyAcc.mean...Y          : num  -0.04051 -0.00131 -0.01614 -0.01738 -0.00992 ...
 $ tBodyAcc.mean...Z          : num  -0.113 -0.105 -0.111 -0.111 -0.108 ...
 $ tBodyAcc.std...X           : num  -0.928 -0.977 -0.996 -0.284 0.03 ...
 $ tBodyAcc.std...Y           : num  -0.8368 -0.9226 -0.9732 0.1145 -0.0319 ...
 $ tBodyAcc.std...Z           : num  -0.826 -0.94 -0.98 -0.26 -0.23 ...
 $ tGravityAcc.mean...X       : num  -0.249 0.832 0.943 0.935 0.932 ...
 $ tGravityAcc.mean...Y       : num  0.706 0.204 -0.273 -0.282 -0.267 ...
 $ tGravityAcc.mean...Z       : num  0.4458 0.332 0.0135 -0.0681 -0.0621 ...
 $ tGravityAcc.std...X        : num  -0.897 -0.968 -0.994 -0.977 -0.951 ...
 $ tGravityAcc.std...Y        : num  -0.908 -0.936 -0.981 -0.971 -0.937 ...
 $ tGravityAcc.std...Z        : num  -0.852 -0.949 -0.976 -0.948 -0.896 ...
 $ tBodyAccJerk.mean...X      : num  0.0811 0.0775 0.0754 0.074 0.0542 ...
 $ tBodyAccJerk.mean...Y      : num  0.003838 -0.000619 0.007976 0.028272 0.02965 ...
 $ tBodyAccJerk.mean...Z      : num  0.01083 -0.00337 -0.00369 -0.00417 -0.01097 ...
 $ tBodyAccJerk.std...X       : num  -0.9585 -0.9864 -0.9946 -0.1136 -0.0123 ...
 $ tBodyAccJerk.std...Y       : num  -0.924 -0.981 -0.986 0.067 -0.102 ...
 $ tBodyAccJerk.std...Z       : num  -0.955 -0.988 -0.992 -0.503 -0.346 ...
 $ tBodyGyro.mean...X         : num  -0.0166 -0.0454 -0.024 -0.0418 -0.0351 ...
 $ tBodyGyro.mean...Y         : num  -0.0645 -0.0919 -0.0594 -0.0695 -0.0909 ...
 $ tBodyGyro.mean...Z         : num  0.1487 0.0629 0.0748 0.0849 0.0901 ...
 $ tBodyGyro.std...X          : num  -0.874 -0.977 -0.987 -0.474 -0.458 ...
 $ tBodyGyro.std...Y          : num  -0.9511 -0.9665 -0.9877 -0.0546 -0.1263 ...
 $ tBodyGyro.std...Z          : num  -0.908 -0.941 -0.981 -0.344 -0.125 ...
 $ tBodyGyroJerk.mean...X     : num  -0.1073 -0.0937 -0.0996 -0.09 -0.074 ...
 $ tBodyGyroJerk.mean...Y     : num  -0.0415 -0.0402 -0.0441 -0.0398 -0.044 ...
 $ tBodyGyroJerk.mean...Z     : num  -0.0741 -0.0467 -0.049 -0.0461 -0.027 ...
 $ tBodyGyroJerk.std...X      : num  -0.919 -0.992 -0.993 -0.207 -0.487 ...
 $ tBodyGyroJerk.std...Y      : num  -0.968 -0.99 -0.995 -0.304 -0.239 ...
 $ tBodyGyroJerk.std...Z      : num  -0.958 -0.988 -0.992 -0.404 -0.269 ...
 $ tBodyAccMag.mean..         : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
 $ tBodyAccMag.std..          : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
 $ tGravityAccMag.mean..      : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
 $ tGravityAccMag.std..       : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
 $ tBodyAccJerkMag.mean..     : num  -0.9544 -0.9874 -0.9924 -0.1414 -0.0894 ...
 $ tBodyAccJerkMag.std..      : num  -0.9282 -0.9841 -0.9931 -0.0745 -0.0258 ...
 $ tBodyGyroMag.mean..        : num  -0.8748 -0.9309 -0.9765 -0.161 -0.0757 ...
 $ tBodyGyroMag.std..         : num  -0.819 -0.935 -0.979 -0.187 -0.226 ...
 $ tBodyGyroJerkMag.mean..    : num  -0.963 -0.992 -0.995 -0.299 -0.295 ...
 $ tBodyGyroJerkMag.std..     : num  -0.936 -0.988 -0.995 -0.325 -0.307 ...
 $ fBodyAcc.mean...X          : num  -0.9391 -0.9796 -0.9952 -0.2028 0.0382 ...
 $ fBodyAcc.mean...Y          : num  -0.86707 -0.94408 -0.97707 0.08971 0.00155 ...
 $ fBodyAcc.mean...Z          : num  -0.883 -0.959 -0.985 -0.332 -0.226 ...
 $ fBodyAcc.std...X           : num  -0.9244 -0.9764 -0.996 -0.3191 0.0243 ...
 $ fBodyAcc.std...Y           : num  -0.834 -0.917 -0.972 0.056 -0.113 ...
 $ fBodyAcc.std...Z           : num  -0.813 -0.934 -0.978 -0.28 -0.298 ...
 $ fBodyAccJerk.mean...X      : num  -0.9571 -0.9866 -0.9946 -0.1705 -0.0277 ...
 $ fBodyAccJerk.mean...Y      : num  -0.9225 -0.9816 -0.9854 -0.0352 -0.1287 ...
 $ fBodyAccJerk.mean...Z      : num  -0.948 -0.986 -0.991 -0.469 -0.288 ...
 $ fBodyAccJerk.std...X       : num  -0.9642 -0.9875 -0.9951 -0.1336 -0.0863 ...
 $ fBodyAccJerk.std...Y       : num  -0.932 -0.983 -0.987 0.107 -0.135 ...
 $ fBodyAccJerk.std...Z       : num  -0.961 -0.988 -0.992 -0.535 -0.402 ...
 $ fBodyGyro.mean...X         : num  -0.85 -0.976 -0.986 -0.339 -0.352 ...
 $ fBodyGyro.mean...Y         : num  -0.9522 -0.9758 -0.989 -0.1031 -0.0557 ...
 $ fBodyGyro.mean...Z         : num  -0.9093 -0.9513 -0.9808 -0.2559 -0.0319 ...
 $ fBodyGyro.std...X          : num  -0.882 -0.978 -0.987 -0.517 -0.495 ...
 $ fBodyGyro.std...Y          : num  -0.9512 -0.9623 -0.9871 -0.0335 -0.1814 ...
 $ fBodyGyro.std...Z          : num  -0.917 -0.944 -0.982 -0.437 -0.238 ...
 $ fBodyAccMag.mean..         : num  -0.8618 -0.9478 -0.9854 -0.1286 0.0966 ...
 $ fBodyAccMag.std..          : num  -0.798 -0.928 -0.982 -0.398 -0.187 ...
 $ fBodyBodyAccJerkMag.mean.. : num  -0.9333 -0.9853 -0.9925 -0.0571 0.0262 ...1
 $ fBodyBodyAccJerkMag.std..  : num  -0.922 -0.982 -0.993 -0.103 -0.104 ...
 $ fBodyBodyGyroMag.mean..    : num  -0.862 -0.958 -0.985 -0.199 -0.186 ...
 $ fBodyBodyGyroMag.std..     : num  -0.824 -0.932 -0.978 -0.321 -0.398 ...
 $ fBodyBodyGyroJerkMag.mean..: num  -0.942 -0.99 -0.995 -0.319 -0.282 ...
 $ fBodyBodyGyroJerkMag.std.. : num  -0.933 -0.987 -0.995 -0.382 -0.392 ...
----------------------------------------------------------------------------------------------   
```        
